'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Report

    '''<summary>
    '''frm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''scriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''tbCLAVE_LOTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCLAVE_LOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbSuperficie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSuperficie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbDepartmentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDepartmentos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbTiendas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTiendas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbGastronomia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbGastronomia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbHotel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHotel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbInstitucional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbInstitucional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNotas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNotas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''updatePnlClave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePnlClave As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''aspTableClaveFill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspTableClaveFill As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aspTableClaveEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspTableClaveEmpty As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvClave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvClave As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbCLAVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCLAVE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCLAVE_ORG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCLAVE_ORG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNOMBRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNOMBRE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNUMERO_PREDIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNUMERO_PREDIO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCALLE_PREDIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCALLE_PREDIO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbUSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUSO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbTIPO_CONST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTIPO_CONST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAREA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAREA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbSEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSEARCH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCLAVEsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCLAVEsearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''aspTableSearchFill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspTableSearchFill As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aspFindCLAVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspFindCLAVE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSearch As Global.System.Web.UI.WebControls.GridView
End Class
